src/Entity/Department.php
<?php

namespace App\Entity;

use App\Repository\DepartmentRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: DepartmentRepository::class)]
class Department
{
    use TimestampableEntity;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;




    #[ORM\OneToMany(mappedBy: 'Department', targetEntity: User::class,cascade: ['persist'], orphanRemoval: true)]
    private Collection $users;

    #[ORM\OneToOne(inversedBy: 'Teammanager', cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $Teammanager = null;



    public function __toString()
    {
     return $this->Name;   
    }
    public function __construct()
    {
        $this->users = new ArrayCollection();

            $this->setCreatedAt(new DateTime());
            $this->setUpdatedAt(new DateTime());
        
    }
   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setDepartment($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getDepartment() === $this) {
                $user->setDepartment(null);
            }
        }

        return $this;
    }

    public function getTeammanager(): ?User
    {
        return $this->Teammanager;
    }

    public function setTeammanager(User $Teammanager): self
    {
        $this->Teammanager = $Teammanager;

        return $this;
    }

 

}

src/Entity/TaskWithProject.php
<?php

namespace App\Entity;

use App\Repository\TaskWithProjectRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;


// #[ORM\HasLifecycleCallbacks]$eventDispatcher->dispatch(

#[ORM\Entity(repositoryClass: TaskWithProjectRepository::class)]
class TaskWithProject
{
    use TimestampableEntity;
    const TASK_STATUS_OPEN = "Open";
    const TASK_STATUS_IN_PROGRESS = "In Progress";
    const TASK_STATUS_COMPLETED = "Completed";
    const TASK_STATUS_ON_HOLD = "On Hold";
    const TASK_STATUS_ARRAY = [TaskWithProject::TASK_STATUS_COMPLETED, TaskWithProject::TASK_STATUS_ON_HOLD, TaskWithProject::TASK_STATUS_OPEN, TaskWithProject::TASK_STATUS_IN_PROGRESS];

    const TASK_PRIORITY_HIGH = "High";
    const TASK_PRIORITY_LOW = "Low";
    const TASK_PRIORITY_MEDIUM = "Medium";


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Priority = null;

    #[ORM\Column(length: 255)]
    private ?string $Status = null;


    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $ActualStartDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\GreaterThanOrEqual(propertyPath: 'ActualStartDate')]
    private ?\DateTimeInterface $ActualEndDate = null;



    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $timer;

    #[ORM\Column]
    private ?int $progress = 0;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'taskWithProjects')]
    private Collection $users;

    #[ORM\ManyToOne(inversedBy: 'taskWithProjects')]
    private ?ProjectDetails $project = null;

    public function __construct()
    {
        $this->timer = new \DateTime('00:00:00');
        $this->setCreatedAt(new DateTime());
        $this->setUpdatedAt(new DateTime());
        $this->users = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->Priority;
    }

    public function setPriority(string $Priority): self
    {
        $this->Priority = $Priority;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(string $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getActualStartDate(): ?\DateTimeInterface
    {
        return $this->ActualStartDate;
    }

    public function setActualStartDate(\DateTimeInterface $ActualStartDate): self
    {
        $this->ActualStartDate = $ActualStartDate;

        return $this;
    }

    public function getActualEndDate(): ?\DateTimeInterface
    {
        return $this->ActualEndDate;
    }

    public function setActualEndDate(?\DateTimeInterface $ActualEndDate): self
    {
        $this->ActualEndDate = $ActualEndDate;

        return $this;
    }



    public function getTimer(): ?\DateTimeInterface
    {
        return $this->timer;
    }

    public function setTimer(?\DateTimeInterface $timer): self
    {
        $this->timer = $timer;

        return $this;
    }

    public function getProgress(): ?int
    {
        return $this->progress;
    }

    public function setProgress(int $progress): self
    {
        $this->progress = $progress;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->users->removeElement($user);

        return $this;
    }

    public function getProject(): ?ProjectDetails
    {
        return $this->project;
    }

    public function setProject(?ProjectDetails $project): self
    {
        $this->project = $project;

        return $this;
    }
    // #[ORM\PreFlush]
    // public function onPrePersist()
    // {
    //  dd($this);   /* write your logic here */
    // }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]


// define(ROLE_USER)="ROLE_USER"
// ROLE_ADMIN="ROLE_PROJECT_MANAGER"
// ROLE_MASTER_ADMIN="ROLE_TEAM_MANAGER"
class User  implements UserInterface, PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;
    const ROLE_USER = "ROLE_USER";
    const ROLE_PROJECT_MANAGER = "ROLE_PROJECT_MANAGER";
    const ROLE_TEAM_MANAGER = "ROLE_TEAM_MANAGER";
    const USER_STATUS_INACTIIVE = "INACTIVE";
    const USER_STATUS_ACTIIVE = "ACTIVE";
    const USER_LOGIN_FROM_PROJECTO = "PROJECTO";
    const USER_LOGIN_FROM_MS_OFFICE = "MS OFFICE";
    const USER_LOGIN_FROM_GOOGLE = "GOOGLE";

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [User::ROLE_USER];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(nullable: true)]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $Firstname;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    private ?string $LastName = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $ContactNumber = null;

    #[ORM\Column(nullable: true)]
    private ?int $exprience = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Department $Department = null;

    #[ORM\OneToOne(mappedBy: 'Teammanager', cascade: ['persist'], orphanRemoval: true)]
    private ?Department $Teammanager = null;

    #[ORM\OneToOne(mappedBy: 'ProjectManager', cascade: ['persist'], orphanRemoval: true)]
    private ?ProjectDetails $projectDetails = null;

    #[ORM\OneToMany(mappedBy: 'User', targetEntity: ProjectAssignment::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $projectAssignment;

    // INACTIIVE,ACTIVE
    #[ORM\Column(length: 255)]
    private ?string $status = User::USER_STATUS_INACTIIVE;

    #[ORM\Column]
    private ?bool $isVerified = false;

    private $plainPassword;

    #[ORM\Column(length: 255)]
    private ?string $loginFrom = User::USER_LOGIN_FROM_PROJECTO;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: DailyAttendance::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $user;

    #[ORM\ManyToMany(targetEntity: TaskWithProject::class, mappedBy: 'users', cascade: ['persist'], orphanRemoval: true)]
    private Collection $taskWithProjects;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist'], orphanRemoval: true)]
    private ?UserProfilePhoto $photoSource = null;

    #[ORM\OneToMany(mappedBy: 'User', targetEntity: OtpAuthentication::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $otpAuthentications;

    #[ORM\ManyToMany(targetEntity: Meetings::class, mappedBy: 'meetingAssignee')]
    private Collection $meetingAssignee;

    #[ORM\OneToMany(mappedBy: 'createdBy', targetEntity: Meetings::class, cascade: ['persist'], orphanRemoval: true)]
    private Collection $meetingCreatedBy;

    #[ORM\Column]
    private ?bool $isDeleted = False;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: ProjectReport::class, orphanRemoval: true)]
    private Collection $projectReports;

    public function __construct()
    {
        $this->setCreatedAt(new DateTime());
        $this->setUpdatedAt(new DateTime());
        $this->user = new ArrayCollection();
        $this->otpAuthentications = new ArrayCollection();
        $this->taskWithProjects = new ArrayCollection();
        $this->meetingAssignee = new ArrayCollection();
        $this->meetingCreatedBy = new ArrayCollection();
        $this->projectAssignment = new ArrayCollection();
        $this->projectReports = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = User::ROLE_USER;

        return array_unique($roles);
    }

    // define(ROLE_USER)="ROLE_USER"
    // ROLE_ADMIN="ROLE_PROJECT_MANAGER"
    // ROLE_MASTER_ADMIN="ROLE_TEAM_MANAGER"
    public function getMainRole(): string
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        return (in_array(User::ROLE_TEAM_MANAGER, $roles)) ? User::ROLE_TEAM_MANAGER : ((in_array(User::ROLE_PROJECT_MANAGER, $roles)) ? User::ROLE_PROJECT_MANAGER : User::ROLE_USER);
    }

    public function setRoles(?array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }
    public function getPlainPassword(): string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $password): self
    {
        $this->plainPassword = $password;

        return $this;
    }
    // public function setPasswordFromPlainPassword(string $password): self
    // {
    //     $userPasswordHasher=$this->userPasswordHasherInterface;
    //     $this->setPassword(
    //         $userPasswordHasher->hashPassword(
    //             $this,
    //             $password
    //         )
    //     );
    //     return $this;
    // }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }
    public function getname(): ?string
    {
        return $this->Firstname . " " . $this->LastName;
    }

    public function setFirstname(?string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(?string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getContactNumber(): ?string
    {
        return $this->ContactNumber;
    }

    public function setContactNumber(?string $ContactNumber): self
    {
        $this->ContactNumber = $ContactNumber;

        return $this;
    }

    public function getExprience(): ?int
    {
        return $this->exprience;
    }

    public function setExprience(?int $exprience): self
    {
        $this->exprience = $exprience;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->Department;
    }

    public function setDepartment(?Department $Department): self
    {
        $this->Department = $Department;

        return $this;
    }

    public function getTeammanager(): ?Department
    {
        return $this->Teammanager;
    }

    public function setTeammanager(Department $Teammanager): self
    {
        // set the owning side of the relation if necessary
        if ($Teammanager->getTeammanager() !== $this) {
            $Teammanager->setTeammanager($this);
        }

        $this->Teammanager = $Teammanager;

        return $this;
    }

    public function getProjectDetails(): ?ProjectDetails
    {
        return $this->projectDetails;
    }

    public function setProjectDetails(ProjectDetails $projectDetails): self
    {
        // set the owning side of the relation if necessary
        if ($projectDetails->getProjectManager() !== $this) {
            $projectDetails->setProjectManager($this);
        }

        $this->projectDetails = $projectDetails;

        return $this;
    }

    // public function getProjectAssignment(): ?ProjectAssignment
    // {
    //     return $this->projectAssignment;
    // }

    // public function setProjectAssignment(ProjectAssignment $projectAssignment): self
    // {
    //     // set the owning side of the relation if necessary
    //     if ($projectAssignment->getUser() !== $this) {
    //         $projectAssignment->setUser($this);
    //     }

    //     $this->projectAssignment = $projectAssignment;

    //     return $this;
    // }

    public function getStatus(): ?string
    {
        return $this->status;
    }
    public function getProfileUrl()
    {
        $url = null;
        if ($this->getPhotoSource()) {
            if ($this->getLoginFrom() == User::USER_LOGIN_FROM_MS_OFFICE) {
                $base64Source = $this->getPhotoSource()->getSource();

templates/parts/_employee_create_form.html.twig
<div class="card">
	<div class="card-body">
		{{ form_start(registrationForm) }}
		{{ form_row(registrationForm.Firstname )  }}
		{{ form_row(registrationForm.LastName) }}
		{{ form_row(registrationForm.ContactNumber)}}
		{{ form_row(registrationForm.email) }}
		{{ form_row(registrationForm.plainPassword, {
                    label: 'Password'
                }) }}
		{{ form_row(registrationForm.agreeTerms) }}
		<button type="submit" class="btn btn-primary" id="registerBtn">Register</button>
		{{ form_end(registrationForm) }}
	</div>
</div>

templates/parts/_form_create_meeting.html.twig
<div class="card">
	<div class="card-body">
		{{ form_start(createMeetingForm) }}
		{{ form_row(createMeetingForm.subject) }}
		{{ form_row(createMeetingForm.meetingStartTime) }}
		{{ form_row(createMeetingForm.meetingEndTime) }}
		{{ form_row(createMeetingForm.meetingAssign) }}
		<button type="submit" class="btn btn-primary">
			Create Meeting
		</button>
		{{ form_end(createMeetingForm) }}
	</div>
</div>

templates/parts/_navbar_common.html.twig
<li class="nav-item">
	<a class="nav-link text-white" aria-current="page" href="{{ path('show_my_checkin_check_out') }}">Check In</a>
</li>

{% if app.user.loginFrom is not null and app.user.loginFrom == constant("App\\Entity\\User::USER_LOGIN_FROM_MS_OFFICE") %}
	<li class="nav-item">
		<a class="nav-link text-white" aria-current="page" href="{{ path('meeting_view') }}">Meetings</a>
	</li>
{% endif %}

templates/parts/_navbar_profile.html.twig
<div class="float-left d-flex">
	<button type="button" id="checkInCheckOutBtn" onclick="checkInCheckOutClick()" value="stop" class="btn btn-outline-light me-2">
		<div class="d-none" id="userId">
			{{ app.user.id }}
		</div>
		<span id="checkInCheckOutTimer" class="d-flex align-items-center">
			<i class="fa fa-play" id="playPauseBtn" aria-hidden="true"></i>
			<div class="hrs">00</div>
			<div class="colon">:</div>
			<div class="min">00</div>
			<div class="colon">:</div>
			<div class="sec">00</div>
		</span>
	</button>
	<div class="btn-group">
		<button type="button" class="btn dropdown-toggle btn-{{ is_granted('ROLE_PREVIOUS_ADMIN') ? 'warning' : 'light' }}" data-bs-toggle="dropdown" aria-expanded="false">
			<img src="{{ app.user.profileUrl }}" referrerpolicy="no-referrer" style="width: 35px; height: 35px;" class="rounded" alt="">
			{{ app.user.name }}
		</button>
		<ul class="dropdown-menu dropdown-menu-end">
			<li>
				<a class="dropdown-item" href="{{ path('profile_page') }}">Profile</a>
			</li>
			{% if is_granted('ROLE_PREVIOUS_ADMIN') %}
				<li>
					<a class="dropdown-item" href="{{ path('check_user_role', {'_switch_user': '_exit'}) }}">Go Back To Main Role</a>
				</li>
			{% else %}
				<li>
					<a class="dropdown-item" href="/logout">Logout</a>
				</li>
			{% endif %}
		</ul>
	</div>
</div>

templates/parts/_show_Meeting.html.twig
{# meeting Object in tabular form #}
{% if pagerFanta is defined %}
	{% set checkCount = pagerFanta.nbResults %}
{% else %}
	{% set checkCount = meetings|length %}
{% endif %}
{% if checkCount > 0 %}
	<div class="container-fluid  mt-5">
		<div class="mt-3">
			<table class=" table-hover table table-bordered">
				<thead>
					<tr>
						<th scope="col">Sr</th>
						<th scope="col">Meeting ID</th>
						<th scope="col">Subject</th>
						<th scope="col">View</th>
					</tr>
				</thead>
				<tbody>
					{% set count = 1 %}
					{% for meeting in meetings %}
						<tr>
							<th scope="row">{{ count }}</th>
							<td>{{ meeting.id }}</td>
							<td>{{ meeting.subject }}</td>
							<td>
								<a href="{{ path('view_single_meeting', { meetingId: meeting.id }) }}" class="btn btn-primary">View</a>
							</td>
						</tr>
						{% set count = count + 1 %}
					{% endfor %}
				</tbody>
			</table>

			{{ pagerfanta(meetings) }}
		</div>
	</div>
{% else %}
	<div class="alert alert-danger" role="alert">
		Oops! No meetings found.
	</div>
{% endif %}

templates/parts/_show_attendance.html.twig
{# this templet renders Array of daily Attendance Object #}
<div class="mt-3">
	{% if allAttendance.nbResults <= 0 %}

		<div class="alert alert-info" role="alert">
			Opps!!! No data till now
		</div>
	{% else %}
		<table class=" table-hover table table-bordered">
			<thead>
				<tr>
					<th scope="col">Sr</th>
					{% if is_granted(constant("App\\Entity\\User::ROLE_TEAM_MANAGER")) or is_granted(constant('App\\Entity\\User::ROLE_PROJECT_MANAGER')) %}
						<th scope="col">User ID</th>
						<th scope="col">User Name</th>
						<th scope="col">User Department</th>
					{% endif %}
					<th scope="col">Timer</th>
					<th scope="col">Date</th>
					<th scope="col">View</th>
				</tr>
			</thead>
			<tbody>
				{% for Attendance in allAttendance %}
					<tr class="expandable-row{{ Attendance.userId == app.user.id ? ' table-primary' : '' }}" data-user-id="{{ users[Attendance.userId].id }}" data-row-id="{{ Attendance.create }}" style="cursor: pointer">
						<th scope="row">{{ loop.index }}</th>
						{% if is_granted(constant("App\\Entity\\User::ROLE_TEAM_MANAGER")) or is_granted(constant('App\\Entity\\User::ROLE_PROJECT_MANAGER')) %}
							<td>{{ users[Attendance.userId].id }}</td>
							<td>{{ users[Attendance.userId].name }}</td>
							<td>{{ users[Attendance.userId].department.name }}</td>
						{% endif %}
						<td>{{ Attendance.timer | date("H:i:s") }}</td>
						<td>{{ Attendance.create | date("d/m/Y") }}</td>
						<td class="expandable-trigger">
							<i class="fas fa-plus" style="color: #3272e2;"></i>
						</td>
					</tr>
					<tr class="expanded-row">
						<td colspan="6">
							<div class="expanded-content" style="display: none;"></div>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		{{ pagerfanta(allAttendance) }}

	{% endif %}
</div>

templates/parts/_show_employee.html.twig
{# this templet renders ProjectAssignment Object #}
<div class="mt-3">
	{% if is_granted(constant("App\\Entity\\User::ROLE_TEAM_MANAGER")) %}
		{# only for team managers #}
		{% if allprojects %}
			{% set checkCount = pagerFanta.nbResults %}
		{% else %}
			{% set checkCount = projectAssign|length %}
		{% endif %}
	{% else %}
		{% if projectReport is defined and projectReport %}
			{% set checkCount = projectAssign|length %}
		{% else %}
			{% set checkCount = projectAssign.nbResults %}
		{% endif %}
	{% endif %}
	{% if checkCount <= 0 %}
		<div class="alert alert-danger" role="alert">
			Oops! No employees found.
		</div>
	{% else %}
		<table class=" table-hover table table-bordered table-hover">
			<thead>
				<tr>
					<th scope="col">Sr</th>
					<th scope="col">User ID</th>
					<th scope="col">User Name</th>
					<th scope="col">User Department</th>
					{% if is_granted(constant("App\\Entity\\User::ROLE_TEAM_MANAGER")) %}
						{% if allprojects %}
							<th scope="col">Project Name</th>
							<th scope="col">Project Description</th>
							<th scope="col">Project Manager Name</th>
						{% endif %}
					{% endif %}
					<th scope="col">Status</th>
				</tr>
			</thead>
			<tbody>
				{% set count = 1 %}
				{% for ProjectAssignment in projectAssign %}
					<tr>
						<th scope="row">{{ count }}</th>
						<td>{{ ProjectAssignment.User.id }}</td>
						<td>{{ ProjectAssignment.User.name }}</td>
						<td>{{ ProjectAssignment.User.Department }}</td>
						{% if projectReport is defined and projectReport %}
							<td>{{ ProjectAssignment.status }}</td>
						{% else %}
							{% if is_granted(constant("App\\Entity\\User::ROLE_TEAM_MANAGER")) %}
								{% if allprojects %}
									<td>{{ ProjectAssignment.project.name }}</td>
									<td>{{ ProjectAssignment.project.description }}</td>
									<td>{{ ProjectAssignment.project.ProjectManager.name }}</td>
								{% endif %}
								{% if ProjectAssignment.status == constant('App\\Entity\\ProjectAssignment::USER_TASK_STATUS_YET_TO_ASSIGN') and app.User.Department == ProjectAssignment.User.Department %}
									<td>
										<div class="d-flex">
											<a class="me-3" href="{{ path('need_approved_change_status', { opration: 'Approved', id: ProjectAssignment.id }) }}">
												<button class="btn btn-success">Approve</button>
											</a>
											<a href="{{ path('need_approved_change_status', { opration: 'Rejected', id: ProjectAssignment.id }) }}">
												<button class="btn btn-danger">Reject</button>
											</a>
										</div>
									</td>
								{% else %}
									<td>{{ ProjectAssignment.status }}</td>
								{% endif %}
							{% else %}
								<td>{{ ProjectAssignment.status }}</td>
							{% endif %}
						{% endif %}
					</tr>
					{% set count = count + 1 %}
				{% endfor %}
			</tbody>
		</table>
		{% if projectReport is defined and projectReport %}
			{# do nothing for project reports #}
		{% else %}
			{# only for team managers #}
			{% if is_granted(constant("App\\Entity\\User::ROLE_TEAM_MANAGER")) %}
				{% if allprojects %}
					{{ pagerfanta(pagerFanta) }}
				{% endif %}
				{# only for project managers #}
			{% else %}
				{{ pagerfanta(projectAssign) }}
			{% endif %}
		{% endif %}
	{% endif %}
</div>

templates/parts/filterEmployee.html.twig
{{ form_start(filterForm,{ 'attr' : { 'class': 'd-flex justify-content-evenly align-self-center align-items-center' } }) }}
{{ form_row(filterForm.searchBy) }}
{{ form_row(filterForm.value,{'required': false}) }}
<button type="submit" class="btn btn-primary">Search</button>
{{ form_end(filterForm) }}